version: "3"

services:
  node-app:
    build: .
    image: eduro-app
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/eduro-assets
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - redis
    volumes:
      - .:/usr/src/
    networks:
      - node-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/var/lib/redis
      # - ./redis/redis-pubsub/redis.conf:/redis.config
    # command: ["redis-server", "/redis.config"]
    networks:
      - node-network

  mongodb:
    image: mongo:4.2.1-bionic
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db
    networks:
      - node-network

volumes:
  dbdata:
  redisdata:

networks:
  node-network:
    driver: bridge
