version: "3"

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/var/lib/redis
      # - ./redis/redis-pubsub/redis.conf:/redis.config
    # command: ["redis-server", "/redis.config"]

  mongodb:
    image: mongo:4.2.1-bionic
    ports:
      - "27020:27017"
    volumes:
      - dbdata:/data/db

volumes:
  dbdata:
  redisdata:
