/** Declaration file generated by dts-gen */

export const version: string;

export function get(url: any, params?: any, callback?: any): any;

export function getAppSecret(): any;

export function post(url: any, postData: any, callback: any): any;

export function search(options: any, callback: any): any;

export function setGraphUrl(url: any): any;

export function setOptions(options: any): any;

export function setVersion(version: any): any;

